# Output configuration
output_base: '/dsl/valleys/cleanup/'

# Processing configuration
params_file: 'params/params_10m.toml'
disable_hyriver_cache: true

# HUC Configuration - USE ONLY ONE OF THE FOLLOWING THREE OPTIONS (comment out the rest):

# Option 1: Single HUC ID
# huc_id: '18050002'

# Option 2: List of specific HUC IDs
#huc_ids:
#- '1802016306'
#- '1804001211'

# Option 3: HUC manfiest with optional filtering and sampling
huc_manifest: './data/target_huc10s.csv' # path to csv with all the huc10s
#prefix: '18'          # Optional: Filter HUCs by prefix
#sample_size: 5              # Optional: Number of HUCs to sample
#random_seed: 14             # Optional: Random seed for sampling
