# Output configuration
output_base: '../outputs/'

# HUC Configuration - USE ONLY ONE OF THE FOLLOWING THREE OPTIONS:

# Option 1: Single HUC ID
# huc_id: '18050002'

# Option 2: List of specific HUC IDs
# huc_ids:
#   - '18050002'
#   - '18050003'
#   - '18050004'

# Option 3: HUC level with filtering and sampling
huc_level: 'huc10'          # One of: huc6, huc8, huc10, huc12
huc_filter: '1805'          # Optional: Filter HUCs by prefix
#sample_size: 5              # Optional: Number of HUCs to sample
#random_seed: 14             # Optional: Random seed for sampling

# Processing configuration
params_file: 'configs/params_10m.toml'
disable_hyriver_cache: true
